#!/bin/bash

FILE=$1
OUTPUT=""

COMMIT_MSG=""

function ask {
    FIELD=$1
    TYPE=$2
    DEFAULT=$3

    echo -n "$FIELD: "
    read INPUT

    if [[ -z "$INPUT" ]]; then
        INPUT=$DEFAULT
    fi
    if [[ "$TYPE" != "int" ]]; then
        INPUT="\"$INPUT\""
    fi

    if [[ "$FIELD" = "title" ]]; then
        COMMIT_MSG="$INPUT"
    fi
    if [[ "$FIELD" = "author" ]]; then
        COMMIT_MSG="$INPUT - $COMMIT_MSG"
    fi

    OUTPUT="$OUTPUT\"$FIELD\": $INPUT, "
}


ask "start_date"
ask "end_date" "string" "$(date +%Y-%m-d)"
ask "language"
ask "year" "int" "$(date +%Y)"
ask "pages" "int" 0
ask "title"
ask "author"
ask "rating" "int" 0
ask "isbn"

OUTPUT=",{$OUTPUT}"
OUTPUT="$(echo "$OUTPUT" | sed "s/, \}$/ \}/")"
echo "$OUTPUT"

echo "ok? [Y/n]"
read CONFIRM

if [[ $CONFIRM =~ ^[Nn]$ ]]; then
    exit 1
fi

sed -i '' $'/\]/i \
    '"$OUTPUT"$'\n' "$FILE"

git add "$FILE"
git commit -m "$(echo "$COMMIT_MSG" | tr -d '"')"
