#!/opt/homebrew/bin/bash

FILE=$1
OUTPUT=""

COMMIT_MSG=""

function ask {
    FIELD=$1
    TYPE=$2
    DEFAULT=$3

    if [[ -z "$DEFAULT" ]]; then
        DEFAULT=""
    fi

    read -e -p "$FIELD: " -i "$DEFAULT" INPUT

    if [[ -z "$INPUT" ]]; then
        INPUT=$DEFAULT
    fi

    if [[ "$FIELD" = "sex" ]]; then
        if [[ "$INPUT" = "m" ]]; then
            INPUT="male"
        elif [[ "$INPUT" = "f" ]]; then
            INPUT="female"
        fi
    fi

    if [[ "$TYPE" != "int" ]]; then
        INPUT="\"$INPUT\""
    fi

    if [[ "$FIELD" = "title" ]]; then
        COMMIT_MSG="$INPUT"
    fi
    if [[ "$FIELD" = "author" ]]; then
        COMMIT_MSG="$INPUT - $COMMIT_MSG"
    fi

    if [[ -n "$INPUT" ]]; then
        OUTPUT="$OUTPUT\"$FIELD\": $INPUT, "
    fi
}

START_DATE=$(cat $FILE | jq '.[-1].end_date' | tr -d '"')

ask "start_date" "string" "$START_DATE"
ask "end_date" "string" "$(date +%Y-%m-%d)"
ask "language"
ask "year" "int" "$(date +%Y)"
ask "pages" "int" 0
ask "title"
ask "author"
ask "sex"
ask "rating" "int" 0
ask "isbn"
ask "country"

OUTPUT=",{$OUTPUT}"
OUTPUT="$(echo "$OUTPUT" | sed "s/, \}$/ \}/")"
echo "$OUTPUT"

if [[ -n "$FILE" ]]; then
    echo "ok? [Y/n]"
    read CONFIRM

    if [[ $CONFIRM =~ ^[Nn]$ ]]; then
        exit 1
    fi

    sed -i '' $'/\]/i \
        '"$OUTPUT"$'\n' "$FILE"

    git add "$FILE"
    git commit -m "$(echo "$COMMIT_MSG" | tr -d '"')"
fi
